### ISSUE TITLE
Allow for async broadcast mode

### ISSUE THREAD

**Issue by albertchon** [InjectiveLabs/sdk-go#11]
We should support all three tx broadcast modes - `Block`, `Sync` and `Async`. 

Currently we only support `Block` mode in `SyncBroadcastMsg` and `Sync` mode in `QueueBroadcastMsg`. 

For consistency, I propose we rename these to 

- `BlockBroadcastMsg`
- `SyncBroadcastMsg`
- `AsyncBroadcastMsg`

FYI enabling async mode is easy enough - just one flag to enable here
https://github.com/InjectiveLabs/sdk-go/commit/ee48e12cd04cab96c54b67bbe4671844678a0069#diff-14d1fe1d4854b5e6a2d53344bc5b613f414c352c1f002899da69ff912bbe1a54R349 (this is in a non-merged separate branch). Obviously should be split/refactored to a proper separate implementation however, as this current one just hijacks the `QueueBroadcastMsg` to be all async

**Comment by xlab** [comment]
The methods are named according to user perspective, instead of making a leaking abstraction over cosmos names.

What we want from `SyncBroadcastMsg ` is to block until Tx is broadcasted. 
What we want from `QueueBroadcastMsg ` is to enqueue the Tx in some form of a queue, where messages are effectively batched into transactions.

These functions cannot be misused, for example if you call them 10 times in parallel, there won't be a nonce issue. They are thread safe and error-prone.

Exposing low-level interface just open possibility for confusion and errors. Every single developer will use `AsyncBroadcastMsg` and will run into nonce issues. Because Cosmos SDK is hard to understand and code with, we make own SDK to provide user-friendly methods, not just aliases to Cosmos low-level types (actually, Tendermint's)

So instead of discussing what should be done (let's rename everything) or how it should be done (let's change a flag), we should discuss why there.

**So my question is, why you would need `AsyncBroadcastMsg` and which is a use case? After  this is settled, I can decide how to extend current API to include the option for that flow too.**

**Comment by xlab** [comment]
It seems that Block mode is discouraged from use as well as it waits for tx on node's side and can exhaust the resources and hand the stuff up. So instead the chain-api client process should be subscribed to events websocket to get Tx confirmations from there. This adds additional layer of problems here, since the client itself is stateless, so events of confirmed Txns should be either polled, or be injected into event queue from outside. I think polling is fine.

**Comment by xlab** [comment]
This patch https://github.com/InjectiveLabs/sdk-go/commit/97aa0a4d04206ccd91f7ce6d00d001bbf3ea6803 addresses the issues described above + bug fixes for the Queue method.

I've also added `AsyncBroadcastMsg`, but keep in mind that it is not related to Tednermint's broadcast mode and trhe purpose of this method is to allow an external scheduler to wait for Tx, instead of internal wait loop as in the new `SyncBroadcastMsg`

**Comment by xlab** [comment]
<img width="719" alt="Screenshot 2021-07-02 at 13 29 28" src="https://user-images.githubusercontent.com/477998/124261577-a43cd100-db39-11eb-8264-f255fcdfccb0.png">
<img width="786" alt="Screenshot 2021-07-02 at 13 29 11" src="https://user-images.githubusercontent.com/477998/124261587-a6069480-db39-11eb-8d0d-68ef8e508ef8.png">
<img width="685" alt="Screenshot 2021-07-02 at 13 29 03" src="https://user-images.githubusercontent.com/477998/124261591-a737c180-db39-11eb-93eb-1c882fe4f68d.png">
