### ISSUE TITLE
StreamDerivativeOrderbookUpdate, StreamOrderbookSnapshot, currently unsupported in production

### ISSUE THREAD

**Issue by ericxor61a0c0d** [InjectiveLabs/sdk-go#88]
https://github.com/InjectiveLabs/sdk-go/blob/eb04b9cee387403b1e7d81e32fef83792380d1f5/client/exchange/exchange.go#L28-L29
This is currently unsupported in devnet, testnet, and mainnet:

```
rpc error: code = Unimplemented desc = unknown method StreamOrderbookSnapshot for service injective_derivative_exchange_rpc.InjectiveDerivativeExchangeRPC
```

**Comment by ericxor61a0c0d** [comment]
`StreamDerivativeOrderbook` is still functional

**Comment by achilleas-kal** [comment]
Clients should refer to the API docs for integrations, SDKs are being updated sooner so we can QA before publishing a new pkg and update the docs. This is a new method currently being tested.

That being said, let's try to merge PRs in SDKs at the same time so that clients don't get confused cc @nhannamsiu @hmoragrega @vinhphuctadang
